"""Exceptions package."""

from app.core.exceptions.base import (
    BaseAppException,
    AuthenticationError,
    InvalidCredentialsError,
    TokenExpiredError,
    InvalidTokenError,
    AuthorizationError,
    InsufficientPermissionsError,
    ResourceNotFoundError,
    UserNotFoundError,
    AppointmentNotFoundError,
    ClientNotFoundError,
    BarberNotFoundError,
    BarbershopNotFoundError,
    ValidationError,
    InvalidTimeSlotError,
    InvalidDateRangeError,
    DuplicateResourceError,
    BusinessLogicError,
    AppointmentConflictError,
    BarberUnavailableError,
    SubscriptionExpiredError,
    SubscriptionLimitReachedError,
    ExternalServiceError,
    EmailServiceError,
    PushNotificationError,
    PaymentServiceError,
)

from app.core.exceptions.handlers import register_exception_handlers

__all__ = [
    "BaseAppException",
    "AuthenticationError",
    "InvalidCredentialsError",
    "TokenExpiredError",
    "InvalidTokenError",
    "AuthorizationError",
    "InsufficientPermissionsError",
    "ResourceNotFoundError",
    "UserNotFoundError",
    "AppointmentNotFoundError",
    "ClientNotFoundError",
    "BarberNotFoundError",
    "BarbershopNotFoundError",
    "ValidationError",
    "InvalidTimeSlotError",
    "InvalidDateRangeError",
    "DuplicateResourceError",
    "BusinessLogicError",
    "AppointmentConflictError",
    "BarberUnavailableError",
    "SubscriptionExpiredError",
    "SubscriptionLimitReachedError",
    "ExternalServiceError",
    "EmailServiceError",
    "PushNotificationError",
    "PaymentServiceError",
    "register_exception_handlers",
]
